// Matheus Bueno Faria R.A.: 2052423
// Natália Yumi Marui de Camargo R.A.: 2142660

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class CadastroAdocao extends javax.swing.JFrame {

     private BancoAdocao ba = new BancoAdocao();
     private Adocao ad = new Adocao();
    public CadastroAdocao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo1 = new javax.swing.JLabel();
        rtNomeTutor = new javax.swing.JLabel();
        rtEndereco = new javax.swing.JLabel();
        rtIdadeTutor = new javax.swing.JLabel();
        rtRG = new javax.swing.JLabel();
        rtTelefone = new javax.swing.JLabel();
        rtTitulo2 = new javax.swing.JLabel();
        rtNomeCachorro = new javax.swing.JLabel();
        rtCodigo = new javax.swing.JLabel();
        rtRaca = new javax.swing.JLabel();
        rtIdadeCachorro = new javax.swing.JLabel();
        rtPeso = new javax.swing.JLabel();
        rtTipoS = new javax.swing.JLabel();
        btSair = new javax.swing.JToggleButton();
        cxNomeTutor = new javax.swing.JTextField();
        cxEndereco = new javax.swing.JTextField();
        cxIdadeTutor = new javax.swing.JTextField();
        cxRG = new javax.swing.JTextField();
        cxTelefone = new javax.swing.JTextField();
        cxNomeCachorro = new javax.swing.JTextField();
        cxCodigo = new javax.swing.JTextField();
        cxRaca = new javax.swing.JTextField();
        cxIdadeCachorro = new javax.swing.JTextField();
        cxPeso = new javax.swing.JTextField();
        cxTipoS = new javax.swing.JTextField();
        rtTitulo3 = new javax.swing.JLabel();
        rtNomeDoador = new javax.swing.JLabel();
        rtAnoAdocao = new javax.swing.JLabel();
        rtCor = new javax.swing.JLabel();
        rtPorte = new javax.swing.JLabel();
        cxNomeDoador = new javax.swing.JTextField();
        cxAnoAdocao = new javax.swing.JTextField();
        cxCor = new javax.swing.JTextField();
        cxPorte = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabAdocao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtTitulo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rtTitulo1.setText("Dados do Tutor:");

        rtNomeTutor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtNomeTutor.setText("Nome:");

        rtEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtEndereco.setText("Endereço:");

        rtIdadeTutor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtIdadeTutor.setText("Idade:");

        rtRG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtRG.setText("RG:");

        rtTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtTelefone.setText("Telefone:");

        rtTitulo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rtTitulo2.setText("Dados do Cachorro: ");

        rtNomeCachorro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtNomeCachorro.setText("Nome:");

        rtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtCodigo.setText("Código:");

        rtRaca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtRaca.setText("Raça:");

        rtIdadeCachorro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtIdadeCachorro.setText("Idade:");

        rtPeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtPeso.setText("Peso:");

        rtTipoS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtTipoS.setText("Tipo Sanguineo:");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        cxRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxRGActionPerformed(evt);
            }
        });

        cxNomeCachorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeCachorroActionPerformed(evt);
            }
        });

        cxTipoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxTipoSActionPerformed(evt);
            }
        });

        rtTitulo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rtTitulo3.setText("Dados de Adoção:");

        rtNomeDoador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtNomeDoador.setText("Nome Doador:");

        rtAnoAdocao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtAnoAdocao.setText("Ano de Adoção:");

        rtCor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtCor.setText("Cor do pelo:");

        rtPorte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rtPorte.setText("Porte do cachorro:");

        btCadastrar.setText("Cadastrar Adoção");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        tabAdocao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Endereço", "Idade", "RG", "Telefone", "Nome cachorro", "Raça", "Idade cachorro", "Peso", "Tipo Sanguíneo", "Nome doador", "Ano adoção", "Cor do pelo", "Porte "
            }
        ));
        tabAdocao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabAdocaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabAdocao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSair)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(rtTelefone)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(rtTitulo2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rtTitulo3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rtTitulo1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(rtCor)
                                    .addGap(27, 27, 27)
                                    .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(rtNomeCachorro)
                                        .addGap(26, 26, 26)
                                        .addComponent(cxNomeCachorro))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rtEndereco)
                                            .addComponent(rtNomeTutor)
                                            .addComponent(rtIdadeTutor))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cxNomeTutor)
                                            .addComponent(cxEndereco)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cxIdadeTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rtRG)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cxRG, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btCadastrar)
                                    .addGap(40, 40, 40)
                                    .addComponent(btLimpar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rtCodigo)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cxRaca, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                                .addComponent(cxCodigo)))
                                        .addComponent(rtRaca))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rtIdadeCachorro)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cxIdadeCachorro))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rtPeso)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(0, 336, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(rtTipoS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxTipoS, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtNomeDoador)
                    .addComponent(rtAnoAdocao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxAnoAdocao, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxNomeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(rtPorte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxPorte, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNomeTutor)
                    .addComponent(cxNomeTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtEndereco)
                    .addComponent(cxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtIdadeTutor)
                    .addComponent(cxIdadeTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtRG)
                    .addComponent(cxRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtTelefone)
                    .addComponent(cxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNomeCachorro)
                    .addComponent(cxNomeCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtCodigo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rtIdadeCachorro)
                        .addComponent(cxIdadeCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtRaca)
                    .addComponent(cxRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtPeso)
                    .addComponent(cxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTipoS)
                    .addComponent(cxTipoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtTitulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNomeDoador)
                    .addComponent(cxNomeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtAnoAdocao)
                    .addComponent(cxAnoAdocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCor)
                    .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtPorte)
                    .addComponent(cxPorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxRGActionPerformed

    private void cxNomeCachorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeCachorroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeCachorroActionPerformed

    private void cxTipoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxTipoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxTipoSActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        ad = new Adocao();
        
        try{
            ad.getTutor1().setNometutor(cxNomeTutor.getText());
            ad.getTutor1().setEnderecotutor(cxEndereco.getText());
            ad.getTutor1().setIdadetutor(Integer.parseInt(cxIdadeTutor.getText()));
            ad.getTutor1().setRgtutor(cxRG.getText());
            ad.getTutor1().setTelefonetutor(Integer.parseInt(cxTelefone.getText()));
            ad.setNomecachorro(cxNomeCachorro.getText());
            ad.setCodigocachorro(Integer.parseInt(cxCodigo.getText()));
            ad.setRacacachorro(cxRaca.getText());
            ad.setIdadecachorro(Integer.parseInt(cxIdadeCachorro.getText()));
            ad.setPesocachorro(Integer.parseInt(cxPeso.getText()));
            ad.setTiposanguineocachorro(cxTipoS.getText());
            ad.setCorpelagem(cxCor.getText());
            ad.setNomedoador(cxNomeDoador.getText());
            ad.setAnoadocao(Integer.parseInt(cxAnoAdocao.getText()));
            ad.setPortecachorro(cxPorte.getText());
                    
             if (cxNomeTutor.getText() != null && cxNomeTutor.getText().length() == 0){ 
            	JOptionPane.showMessageDialog(null, "CAMPO NOME DO TUTOR NÃO PODE SER NULO","ERRO!!", JOptionPane.ERROR_MESSAGE);
            	cxNomeTutor.setText("");
            	cxNomeTutor.requestFocus();
           
            }
            
            else if (cxEndereco.getText() != null && cxEndereco.getText().length() == 0){ 
            	JOptionPane.showMessageDialog(null, "CAMPO ENDEREÇO NÃO PODE SER NULO","ERRO!!", JOptionPane.ERROR_MESSAGE);
            	cxEndereco.setText("");
            	cxEndereco.requestFocus();
           
            } 
            
            else if (cxNomeCachorro.getText() != null && cxNomeCachorro.getText().length() == 0){ 
            	JOptionPane.showMessageDialog(null, "CAMPO NOME DO ANIMAL NÃO PODE SER NULO","ERRO!!", JOptionPane.ERROR_MESSAGE);
            	cxNomeCachorro.setText("");
            	cxNomeCachorro.requestFocus();
           
            } 
            
            else if (cxRaca.getText() != null && cxRaca.getText().length() == 0){ 
            	JOptionPane.showMessageDialog(null, "CAMPO RAÇA NÃO PODE SER NULO","ERRO!!", JOptionPane.ERROR_MESSAGE);
            	cxRaca.setText("");
            	cxRaca.requestFocus();
           
            } 
            
            else if (cxTipoS.getText() != null && cxTipoS.getText().length() == 0){ 
            	JOptionPane.showMessageDialog(null, "CAMPO TIPO SANGUÍNEO NÃO PODE SER NULO","ERRO!!", JOptionPane.ERROR_MESSAGE);
            	cxTipoS.setText("");
            	cxTipoS.requestFocus();
           
            } 
            
            else if (cxCor.getText() != null && cxCor.getText().length() == 0){ 
            	JOptionPane.showMessageDialog(null, "CAMPO COR NÃO PODE SER NULO","ERRO!!", JOptionPane.ERROR_MESSAGE);
            	cxCor.setText("");
            	cxCor.requestFocus();
           
            } 
            
            else if (cxNomeDoador.getText() != null && cxNomeDoador.getText().length() == 0){ 
            	JOptionPane.showMessageDialog(null, "CAMPO NOME DOADOR NÃO PODE SER NULO","ERRO!!", JOptionPane.ERROR_MESSAGE);
            	cxNomeDoador.setText("");
            	cxNomeDoador.requestFocus();
           
            } 
            
            else if (ba.consultaADCOD(ad) == null){
                ba.getBDA().add(ad);
                JOptionPane.showMessageDialog(null, "Adoção cadastrada com SUCESSO!!!", "SUCESSO!!", JOptionPane.INFORMATION_MESSAGE);
                cxNomeTutor.setText("");
                cxEndereco.setText("");
                cxIdadeTutor.setText("");
                cxRG.setText("");
                cxTelefone.setText("");
                cxNomeCachorro.setText("");
                cxCodigo.setText("");
                cxRaca.setText("");
                cxIdadeCachorro.setText("");
                cxPeso.setText("");
                cxTipoS.setText("");
                cxCor.setText("");
                cxNomeDoador.setText("");
                cxPorte.setText("");
                cxAnoAdocao.setText("");
                cxNomeTutor.requestFocus();
                showTabAdocao();
                
            }
            
            else {
                JOptionPane.showMessageDialog (null, "Código já EXISTENTE!!","ERRO!!", JOptionPane.ERROR_MESSAGE);
                cxCodigo.setText("");
                cxCodigo.requestFocus();
            }
            
            
        }
        catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "A IDADE, TELEFONE, CÓDIGO, PESO, ANO devem ser valores INTEIROS!","ERRO!!", JOptionPane.ERROR_MESSAGE);
            cxCodigo.setText("");
            cxIdadeTutor.setText("");
            cxIdadeCachorro.setText("");
            cxTelefone.setText("");
            cxPeso.setText("");
            cxAnoAdocao.setText("");
            cxIdadeTutor.requestFocus();
        }
        catch (PorteException porte){
            JOptionPane.showMessageDialog (null, "O porte deve ser MÉDIO, GRANDE, PEQUENO, MINI, INDEFINIDO", "ERRO!!", JOptionPane.ERROR_MESSAGE);
            cxPorte.setText("");
            cxPorte.requestFocus();
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
                
                cxNomeTutor.setText("");
                cxEndereco.setText("");
                cxIdadeTutor.setText("");
                cxRG.setText("");
                cxTelefone.setText("");
                cxNomeCachorro.setText("");
                cxCodigo.setText("");
                cxRaca.setText("");
                cxIdadeCachorro.setText("");
                cxPeso.setText("");
                cxTipoS.setText("");
                cxCor.setText("");
                cxNomeDoador.setText("");
                cxPorte.setText("");
                cxAnoAdocao.setText("");
                cxNomeTutor.requestFocus();
                
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void tabAdocaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabAdocaoMouseClicked
        String nomeComponente = "";
        int coluna;
        
        int posLinha = tabAdocao.getSelectedRow();
        for ( coluna = 0; coluna<tabAdocao.getColumnCount(); coluna ++){
            nomeComponente += tabAdocao.getModel().getValueAt(posLinha,coluna).toString();
            
        
            if(coluna < tabAdocao.getColumnCount()){
                nomeComponente += "-";
            }
        }
        JOptionPane.showMessageDialog(null, "Você escolheu o cadastro: " +nomeComponente);
    
    }//GEN-LAST:event_tabAdocaoMouseClicked
    public void showTabAdocao(){
        Adocao ad = new Adocao();
        DefaultTableModel modTabAD = new DefaultTableModel();
        modTabAD= (DefaultTableModel) tabAdocao.getModel();
        modTabAD.setRowCount(0);
        
        for (int posLinha=0; posLinha < ba.getBDA().size(); posLinha ++){
            ad.setCodigocachorro(ba.getBDA().get(posLinha).getCodigocachorro());
            ad.getTutor1().setNometutor(ba.getBDA().get(posLinha).getTutor1().getNometutor());
            ad.getTutor1().setEnderecotutor(ba.getBDA().get(posLinha).getTutor1().getEnderecotutor());
            ad.getTutor1().setIdadetutor(ba.getBDA().get(posLinha).getTutor1().getIdadetutor());
            ad.getTutor1().setRgtutor(ba.getBDA().get(posLinha).getTutor1().getRgtutor());
            ad.getTutor1().setTelefonetutor(ba.getBDA().get(posLinha).getTutor1().getTelefonetutor());
            ad.setNomecachorro(ba.getBDA().get(posLinha).getNomecachorro());
            ad.setRacacachorro(ba.getBDA().get(posLinha).getRacacachorro());
            ad.setIdadecachorro(ba.getBDA().get(posLinha).getIdadecachorro());
            ad.setPesocachorro(ba.getBDA().get(posLinha).getPesocachorro());
            ad.setTiposanguineocachorro(ba.getBDA().get(posLinha).getTiposanguineocachorro());
            ad.setNomedoador(ba.getBDA().get(posLinha).getNomedoador());
            ad.setAnoadocao(ba.getBDA().get(posLinha).getAnoadocao());
            ad.setCorpelagem(ba.getBDA().get(posLinha).getCorpelagem());
            try {
                ad.setPortecachorro(ba.getBDA().get(posLinha).getPortecachorro());
            } catch (PorteException ex) {
                
            }
            
            
            modTabAD.insertRow(posLinha, new Object[]{ad.getCodigocachorro(), ad.getTutor1().getNometutor(), ad.getTutor1().getEnderecotutor(), ad.getTutor1().getIdadetutor(), ad.getTutor1().getRgtutor(), ad.getTutor1().getTelefonetutor(),ad.getNomecachorro(),ad.getRacacachorro(),ad.getIdadecachorro(),ad.getPesocachorro(),ad.getTiposanguineocachorro(),ad.getNomedoador(),ad.getAnoadocao(),ad.getCorpelagem(),ad.getPortecachorro()});
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAdocao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JToggleButton btSair;
    private javax.swing.JTextField cxAnoAdocao;
    private javax.swing.JTextField cxCodigo;
    private javax.swing.JTextField cxCor;
    private javax.swing.JTextField cxEndereco;
    private javax.swing.JTextField cxIdadeCachorro;
    private javax.swing.JTextField cxIdadeTutor;
    private javax.swing.JTextField cxNomeCachorro;
    private javax.swing.JTextField cxNomeDoador;
    private javax.swing.JTextField cxNomeTutor;
    private javax.swing.JTextField cxPeso;
    private javax.swing.JTextField cxPorte;
    private javax.swing.JTextField cxRG;
    private javax.swing.JTextField cxRaca;
    private javax.swing.JTextField cxTelefone;
    private javax.swing.JTextField cxTipoS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtAnoAdocao;
    private javax.swing.JLabel rtCodigo;
    private javax.swing.JLabel rtCor;
    private javax.swing.JLabel rtEndereco;
    private javax.swing.JLabel rtIdadeCachorro;
    private javax.swing.JLabel rtIdadeTutor;
    private javax.swing.JLabel rtNomeCachorro;
    private javax.swing.JLabel rtNomeDoador;
    private javax.swing.JLabel rtNomeTutor;
    private javax.swing.JLabel rtPeso;
    private javax.swing.JLabel rtPorte;
    private javax.swing.JLabel rtRG;
    private javax.swing.JLabel rtRaca;
    private javax.swing.JLabel rtTelefone;
    private javax.swing.JLabel rtTipoS;
    private javax.swing.JLabel rtTitulo1;
    private javax.swing.JLabel rtTitulo2;
    private javax.swing.JLabel rtTitulo3;
    private javax.swing.JTable tabAdocao;
    // End of variables declaration//GEN-END:variables
}
